### ISSUE TITLE
Editor :: users cannot delete content from media library

### ISSUE THREAD

**Issue by ahmedmkabil** [Zeega/Zeega#1402] opened 2013-01-03 19:41 UTC
-Add content to Zeega.
-Attempt to delete content from media library in Zeega editor.
-After pressing 'okay' to delete item, nothing happens and item remains in library.

**Comment by jshapins** [comment] 2013-01-03 19:43
This is a duplicate of #1395

**Closed as completed by jshapins** 2013-01-03 19:43 UTC
Labels: bug
