### ISSUE TITLE
JDA - pasting text into search box hides text

### ISSUE THREAD

**Issue by kmlawson** [Zeega/Zeega#470] opened 2012-03-06 17:08 UTC
Chrome 17.0.963 OS X - pasting any text into the search box (not on the main home page but on the list or time/space view), like "Japan reconstruction" obscures the pasted text. Pressing enter shows the text again.

**Comment by jshapins** [comment] 2012-03-06 17:15
This is a duplicate of issue #418. Problem resides with DocumentCloud. Exists on their site, too.

**Closed as completed by jshapins** 2012-03-06 17:15 UTC

**Comment by jbergen** [comment] 2012-03-06 18:39
This is a bug with the VisualSearch. Pasted text doesn't always come in with dimensions

-mobilejoseph
